/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutViewSystemUserRouteImport } from './routes/_layout/view/system/user'
import { Route as LayoutViewSystemMenuRouteImport } from './routes/_layout/view/system/menu'
import { Route as LayoutViewSystemCmmonCodeRouteImport } from './routes/_layout/view/system/cmmonCode'
import { Route as LayoutViewOutboundManageRouteImport } from './routes/_layout/view/outbound/manage'
import { Route as LayoutViewOrderManageRouteImport } from './routes/_layout/view/order/manage'
import { Route as LayoutViewMaterialInboundRouteImport } from './routes/_layout/view/material/inbound'
import { Route as LayoutViewMasterBomRouteImport } from './routes/_layout/view/master/bom'
import { Route as LayoutViewInventoryListRouteImport } from './routes/_layout/view/inventory/list'
import { Route as LayoutViewInboundManageRouteImport } from './routes/_layout/view/inbound/manage'
import { Route as LayoutViewMasterItemListRouteImport } from './routes/_layout/view/master/item/list'
import { Route as LayoutViewMasterCustomerListRouteImport } from './routes/_layout/view/master/customer/list'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutViewSystemUserRoute = LayoutViewSystemUserRouteImport.update({
  id: '/view/system/user',
  path: '/view/system/user',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutViewSystemMenuRoute = LayoutViewSystemMenuRouteImport.update({
  id: '/view/system/menu',
  path: '/view/system/menu',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutViewSystemCmmonCodeRoute =
  LayoutViewSystemCmmonCodeRouteImport.update({
    id: '/view/system/cmmonCode',
    path: '/view/system/cmmonCode',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutViewOutboundManageRoute =
  LayoutViewOutboundManageRouteImport.update({
    id: '/view/outbound/manage',
    path: '/view/outbound/manage',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutViewOrderManageRoute = LayoutViewOrderManageRouteImport.update({
  id: '/view/order/manage',
  path: '/view/order/manage',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutViewMaterialInboundRoute =
  LayoutViewMaterialInboundRouteImport.update({
    id: '/view/material/inbound',
    path: '/view/material/inbound',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutViewMasterBomRoute = LayoutViewMasterBomRouteImport.update({
  id: '/view/master/bom',
  path: '/view/master/bom',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutViewInventoryListRoute = LayoutViewInventoryListRouteImport.update({
  id: '/view/inventory/list',
  path: '/view/inventory/list',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutViewInboundManageRoute = LayoutViewInboundManageRouteImport.update({
  id: '/view/inbound/manage',
  path: '/view/inbound/manage',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutViewMasterItemListRoute =
  LayoutViewMasterItemListRouteImport.update({
    id: '/view/master/item/list',
    path: '/view/master/item/list',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutViewMasterCustomerListRoute =
  LayoutViewMasterCustomerListRouteImport.update({
    id: '/view/master/customer/list',
    path: '/view/master/customer/list',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof LayoutIndexRoute
  '/view/inbound/manage': typeof LayoutViewInboundManageRoute
  '/view/inventory/list': typeof LayoutViewInventoryListRoute
  '/view/master/bom': typeof LayoutViewMasterBomRoute
  '/view/material/inbound': typeof LayoutViewMaterialInboundRoute
  '/view/order/manage': typeof LayoutViewOrderManageRoute
  '/view/outbound/manage': typeof LayoutViewOutboundManageRoute
  '/view/system/cmmonCode': typeof LayoutViewSystemCmmonCodeRoute
  '/view/system/menu': typeof LayoutViewSystemMenuRoute
  '/view/system/user': typeof LayoutViewSystemUserRoute
  '/view/master/customer/list': typeof LayoutViewMasterCustomerListRoute
  '/view/master/item/list': typeof LayoutViewMasterItemListRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof LayoutIndexRoute
  '/view/inbound/manage': typeof LayoutViewInboundManageRoute
  '/view/inventory/list': typeof LayoutViewInventoryListRoute
  '/view/master/bom': typeof LayoutViewMasterBomRoute
  '/view/material/inbound': typeof LayoutViewMaterialInboundRoute
  '/view/order/manage': typeof LayoutViewOrderManageRoute
  '/view/outbound/manage': typeof LayoutViewOutboundManageRoute
  '/view/system/cmmonCode': typeof LayoutViewSystemCmmonCodeRoute
  '/view/system/menu': typeof LayoutViewSystemMenuRoute
  '/view/system/user': typeof LayoutViewSystemUserRoute
  '/view/master/customer/list': typeof LayoutViewMasterCustomerListRoute
  '/view/master/item/list': typeof LayoutViewMasterItemListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/view/inbound/manage': typeof LayoutViewInboundManageRoute
  '/_layout/view/inventory/list': typeof LayoutViewInventoryListRoute
  '/_layout/view/master/bom': typeof LayoutViewMasterBomRoute
  '/_layout/view/material/inbound': typeof LayoutViewMaterialInboundRoute
  '/_layout/view/order/manage': typeof LayoutViewOrderManageRoute
  '/_layout/view/outbound/manage': typeof LayoutViewOutboundManageRoute
  '/_layout/view/system/cmmonCode': typeof LayoutViewSystemCmmonCodeRoute
  '/_layout/view/system/menu': typeof LayoutViewSystemMenuRoute
  '/_layout/view/system/user': typeof LayoutViewSystemUserRoute
  '/_layout/view/master/customer/list': typeof LayoutViewMasterCustomerListRoute
  '/_layout/view/master/item/list': typeof LayoutViewMasterItemListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/'
    | '/view/inbound/manage'
    | '/view/inventory/list'
    | '/view/master/bom'
    | '/view/material/inbound'
    | '/view/order/manage'
    | '/view/outbound/manage'
    | '/view/system/cmmonCode'
    | '/view/system/menu'
    | '/view/system/user'
    | '/view/master/customer/list'
    | '/view/master/item/list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/view/inbound/manage'
    | '/view/inventory/list'
    | '/view/master/bom'
    | '/view/material/inbound'
    | '/view/order/manage'
    | '/view/outbound/manage'
    | '/view/system/cmmonCode'
    | '/view/system/menu'
    | '/view/system/user'
    | '/view/master/customer/list'
    | '/view/master/item/list'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/'
    | '/_layout/view/inbound/manage'
    | '/_layout/view/inventory/list'
    | '/_layout/view/master/bom'
    | '/_layout/view/material/inbound'
    | '/_layout/view/order/manage'
    | '/_layout/view/outbound/manage'
    | '/_layout/view/system/cmmonCode'
    | '/_layout/view/system/menu'
    | '/_layout/view/system/user'
    | '/_layout/view/master/customer/list'
    | '/_layout/view/master/item/list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/view/system/user': {
      id: '/_layout/view/system/user'
      path: '/view/system/user'
      fullPath: '/view/system/user'
      preLoaderRoute: typeof LayoutViewSystemUserRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/view/system/menu': {
      id: '/_layout/view/system/menu'
      path: '/view/system/menu'
      fullPath: '/view/system/menu'
      preLoaderRoute: typeof LayoutViewSystemMenuRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/view/system/cmmonCode': {
      id: '/_layout/view/system/cmmonCode'
      path: '/view/system/cmmonCode'
      fullPath: '/view/system/cmmonCode'
      preLoaderRoute: typeof LayoutViewSystemCmmonCodeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/view/outbound/manage': {
      id: '/_layout/view/outbound/manage'
      path: '/view/outbound/manage'
      fullPath: '/view/outbound/manage'
      preLoaderRoute: typeof LayoutViewOutboundManageRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/view/order/manage': {
      id: '/_layout/view/order/manage'
      path: '/view/order/manage'
      fullPath: '/view/order/manage'
      preLoaderRoute: typeof LayoutViewOrderManageRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/view/material/inbound': {
      id: '/_layout/view/material/inbound'
      path: '/view/material/inbound'
      fullPath: '/view/material/inbound'
      preLoaderRoute: typeof LayoutViewMaterialInboundRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/view/master/bom': {
      id: '/_layout/view/master/bom'
      path: '/view/master/bom'
      fullPath: '/view/master/bom'
      preLoaderRoute: typeof LayoutViewMasterBomRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/view/inventory/list': {
      id: '/_layout/view/inventory/list'
      path: '/view/inventory/list'
      fullPath: '/view/inventory/list'
      preLoaderRoute: typeof LayoutViewInventoryListRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/view/inbound/manage': {
      id: '/_layout/view/inbound/manage'
      path: '/view/inbound/manage'
      fullPath: '/view/inbound/manage'
      preLoaderRoute: typeof LayoutViewInboundManageRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/view/master/item/list': {
      id: '/_layout/view/master/item/list'
      path: '/view/master/item/list'
      fullPath: '/view/master/item/list'
      preLoaderRoute: typeof LayoutViewMasterItemListRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/view/master/customer/list': {
      id: '/_layout/view/master/customer/list'
      path: '/view/master/customer/list'
      fullPath: '/view/master/customer/list'
      preLoaderRoute: typeof LayoutViewMasterCustomerListRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutViewInboundManageRoute: typeof LayoutViewInboundManageRoute
  LayoutViewInventoryListRoute: typeof LayoutViewInventoryListRoute
  LayoutViewMasterBomRoute: typeof LayoutViewMasterBomRoute
  LayoutViewMaterialInboundRoute: typeof LayoutViewMaterialInboundRoute
  LayoutViewOrderManageRoute: typeof LayoutViewOrderManageRoute
  LayoutViewOutboundManageRoute: typeof LayoutViewOutboundManageRoute
  LayoutViewSystemCmmonCodeRoute: typeof LayoutViewSystemCmmonCodeRoute
  LayoutViewSystemMenuRoute: typeof LayoutViewSystemMenuRoute
  LayoutViewSystemUserRoute: typeof LayoutViewSystemUserRoute
  LayoutViewMasterCustomerListRoute: typeof LayoutViewMasterCustomerListRoute
  LayoutViewMasterItemListRoute: typeof LayoutViewMasterItemListRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutViewInboundManageRoute: LayoutViewInboundManageRoute,
  LayoutViewInventoryListRoute: LayoutViewInventoryListRoute,
  LayoutViewMasterBomRoute: LayoutViewMasterBomRoute,
  LayoutViewMaterialInboundRoute: LayoutViewMaterialInboundRoute,
  LayoutViewOrderManageRoute: LayoutViewOrderManageRoute,
  LayoutViewOutboundManageRoute: LayoutViewOutboundManageRoute,
  LayoutViewSystemCmmonCodeRoute: LayoutViewSystemCmmonCodeRoute,
  LayoutViewSystemMenuRoute: LayoutViewSystemMenuRoute,
  LayoutViewSystemUserRoute: LayoutViewSystemUserRoute,
  LayoutViewMasterCustomerListRoute: LayoutViewMasterCustomerListRoute,
  LayoutViewMasterItemListRoute: LayoutViewMasterItemListRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
