# 📦 GitHub Actions Workflow: Build and Deploy with Manual or Auto Trigger

name: Build and Deploy

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: '배포 환경 (dev 또는 prod)'
        required: true
        default: 'dev'
      module:
        description: '배포할 모듈명 (예: bizcof-wms-app 또는 bizcof-mes-app)'
        required: true
        default: 'bizcof-wms-app'

# 전역 환경 변수
env:
  JAVA_VERSION: '17'                            # 사용할 Java 버전
  JAVA_DISTRIBUTION: 'temurin'                 # Temurin JDK 사용
  TARGET_SERVER_IP_DEV: 192.168.0.13           # dev 환경 대상 서버 IP
  TARGET_SERVER_IP_PROD: 192.168.0.14          # prod 환경 대상 서버 IP
  REMOTE_USER: root                            # 배포할 서버 사용자

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || github.event_name == 'workflow_dispatch'
    env:
      MODULE_NAME: ${{ github.event.inputs.module || 'bizcof-wms-app' }}
    steps:
      - uses: actions/checkout@v3                  # GitHub 저장소 코드 체크아웃

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build the module
        run: |
          ./gradlew :${MODULE_NAME}:clean :${MODULE_NAME}:build -x test
          ls -la ${MODULE_NAME}/build/libs

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.MODULE_NAME }}-jar
          path: ${{ env.MODULE_NAME }}/build/libs/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop' || github.event_name == 'workflow_dispatch'
    env:
      MODULE_NAME: ${{ github.event.inputs.module || 'bizcof-wms-app' }}
      ENV_PROFILE: ${{ github.event.inputs.environment || 'dev' }}
    steps:
      - uses: actions/checkout@v3

      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.MODULE_NAME }}-jar
          path: ./artifact                    # 다운로드 위치 지정

      - name: Set JAR path
        run: |
          JAR_PATH=$(find ./artifact -name "${MODULE_NAME}-*.jar" | head -n 1)
          if [ -z "$JAR_PATH" ]; then echo "JAR not found!"; exit 1; fi
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV

      - name: Determine server IP by profile
        run: |
          if [[ "$ENV_PROFILE" == "prod" ]]; then
            echo "SERVER_IP=$TARGET_SERVER_IP_PROD" >> $GITHUB_ENV
          else
            echo "SERVER_IP=$TARGET_SERVER_IP_DEV" >> $GITHUB_ENV
          fi

      - name: Deploy to Remote Server via SCP and SSH
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # 원격 서버 경로 생성 및 JAR 파일 전송
          ssh -o StrictHostKeyChecking=no -i private_key.pem $REMOTE_USER@$SERVER_IP \
            "mkdir -p /app/servers/${MODULE_NAME}"

          scp -o StrictHostKeyChecking=no -i private_key.pem "$JAR_PATH" $REMOTE_USER@$SERVER_IP:/app/servers/${MODULE_NAME}/

          # 시스템 서비스 재시작 및 상태 확인
          ssh -o StrictHostKeyChecking=no -i private_key.pem $REMOTE_USER@$SERVER_IP \
            "sudo systemctl restart ${MODULE_NAME}.service"

          ssh -o StrictHostKeyChecking=no -i private_key.pem $REMOTE_USER@$SERVER_IP \
            "sudo systemctl status ${MODULE_NAME}.service"
